repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [--preview]
      - id: ruff-format
        args: [--check, --diff, --preview]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - boto3-stubs[essential]>=1.26.0
          - types-requests>=2.28.0

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--configfile, .bandit, --format, json]
        exclude: ^tests/


