name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      contents: read
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Install Node.js for CDK CLI
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install CDK CLI and security tools
      run: |
        npm install -g aws-cdk
        pip install semgrep checkov
        
    - name: Run Bandit security scan
      run: |
        bandit -r . -f json -o bandit-report.json
      continue-on-error: true
      
    - name: Run Semgrep security scan
      run: |
        semgrep --config=auto --json --output=semgrep-report.json .
      continue-on-error: true
      
    - name: Synthesize CloudFormation templates
      run: cdk synth --all
      env:
        CDK_DEFAULT_ACCOUNT: "645166163764"
        CDK_DEFAULT_REGION: "us-east-1"
        
    - name: Run Checkov on CloudFormation templates
      run: |
        checkov -d cdk.out --framework cloudformation --output json --output-file checkov-report.json
      continue-on-error: true
      
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          semgrep-report.json
          checkov-report.json
          
    - name: Generate security summary
      run: |
        echo "## 🔒 Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "Security scans completed for commit ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Scans Performed:" >> $GITHUB_STEP_SUMMARY
        echo "- **Bandit:** Python security analysis" >> $GITHUB_STEP_SUMMARY
        echo "- **Semgrep:** Multi-language security patterns" >> $GITHUB_STEP_SUMMARY
        echo "- **Checkov:** CloudFormation security best practices" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📊 Detailed results are available in the uploaded artifacts." >> $GITHUB_STEP_SUMMARY